### ISSUE TITLE
Infinity Symbol Not Showing When You Queue ANY Radio Station Stream (this applies to all dabBot's)

### ISSUE THREAD

**Issue by Xastreh** [dabbotorg/JavaMusicBot#86]
Queuing on dabBot Demo: http://prntscr.com/gkevl1
Queuing on the main bot: http://prntscr.com/gkeyxz
Queuing on dabBot Patron 1: http://prntscr.com/gkf06p
Queuing on dabBot Patron 2: http://prntscr.com/gkf0ye

These are all different streams (or at least should be). Everytime I've done this, not one infinity symbol to be found. And don't question why I showed proof on all the dabBot's. It was just my choice. 😄

**Comment by DoNotSpamPls** [comment]
This bug still happens.
